import { useRef, useState } from "react"
import { CheckCircle2, CircleAlert, ListChecks, X } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Sheet, SheetBackdrop, SheetContent, SheetDescription, SheetPortal, SheetTitle } from "@/components/ui/sheet"
import type { ManualDeleteBatch, ManualDeleteJob } from "@/lib/library"
import { localizedBatchStatus, localizedJobPhase, type DeletionLanguage } from "@/features/deletion/deletion-copy"

export function JobsSheet({ jobs, batches = [], title, activeLabel, recentLabel, dismissLabel, closeLabel, progressLabel, language, announcement, announcementTone, onDismiss }: { jobs: ManualDeleteJob[]; batches?: ManualDeleteBatch[]; title: string; activeLabel: string; recentLabel: string; dismissLabel: string; closeLabel: string; progressLabel: string; language: DeletionLanguage; announcement: string | null; announcementTone: "polite" | "assertive"; onDismiss: (id: string) => void }) {
  const [open, setOpen] = useState(false)
  const triggerRef = useRef<HTMLButtonElement>(null)
  const sheetId = "delete-jobs-sheet"
  const activeCount = jobs.filter(isActive).length + batches.filter(isBatchActive).length
  const totalCount = jobs.length + batches.length
  const summary = activeCount ? taskCountLabel(activeCount, "active", language, activeLabel) : taskCountLabel(totalCount, "recent", language, recentLabel)
  return <><div aria-live={announcementTone} aria-atomic="true" className="sr-only">{announcement}</div>{totalCount ? <div className="mx-auto flex max-w-6xl justify-end px-4 pb-4 sm:px-6"><Button ref={triggerRef} variant="outline" size="sm" onClick={() => setOpen(true)} aria-expanded={open} aria-controls={sheetId} aria-label={title}><ListChecks className="size-4" />{summary}</Button></div> : null}<Sheet open={open} onOpenChange={setOpen}><SheetPortal><SheetBackdrop className="fixed inset-0 z-50 bg-foreground/20" /><SheetContent id={sheetId} finalFocus={triggerRef} className="fixed inset-y-0 right-0 z-50 flex w-[min(100%,26rem)] flex-col border-l border-border bg-background shadow-2xl"><div className="flex items-start justify-between border-b border-border p-4"><div><SheetTitle className="font-semibold">{title}</SheetTitle><SheetDescription className="text-sm text-muted-foreground">{summary}</SheetDescription></div><Button variant="ghost" size="icon-sm" onClick={() => setOpen(false)} aria-label={closeLabel}><X className="size-4" /></Button></div><ScrollArea className="min-h-0 flex-1 p-3"><div className="space-y-2 pr-2">{batches.map((batch) => <BatchCard key={batch.id} batch={batch} language={language} progressLabel={progressLabel} />)}{jobs.map((job) => <JobCard key={job.id} job={job} language={language} dismissLabel={dismissLabel} progressLabel={progressLabel} onDismiss={onDismiss} />)}</div></ScrollArea></SheetContent></SheetPortal></Sheet></>
}

function JobCard({ job, language, dismissLabel, progressLabel, onDismiss }: { job: ManualDeleteJob; language: DeletionLanguage; dismissLabel: string; progressLabel: string; onDismiss: (id: string) => void }) { const active = isActive(job); const failed = job.status === "failed" || job.result?.status === "partial_failure"; const name = job.display_name; return <article className="rounded-lg border border-border bg-card p-3"><div className="flex gap-2"><div className="pt-0.5">{failed ? <CircleAlert className="size-4 text-status-danger" /> : active ? <ListChecks className="size-4 text-primary" /> : <CheckCircle2 className="size-4 text-status-success" />}</div><div className="min-w-0 flex-1"><div className="flex gap-2"><h3 className="min-w-0 flex-1 truncate text-sm font-medium" title={name}>{name}</h3>{!active ? <Button variant="ghost" size="icon-xs" aria-label={`${dismissLabel}: ${name}`} onClick={() => onDismiss(job.id)}><X className="size-3.5" /></Button> : null}</div><p className="mt-1 text-xs text-muted-foreground">{localizedJobPhase(job.phase, failed, language)}</p><Progress className="mt-3" value={job.progress_percent} aria-label={`${name}: ${progressLabel}`} /><div className="mt-1.5 flex justify-between gap-2 text-[11px] text-muted-foreground"><Badge variant="outline" className="text-[10px]">{localizedJobPhase(job.phase, failed, language)}</Badge><span>{job.progress_percent}%</span></div></div></div></article> }
function isActive(job: ManualDeleteJob) { return job.status === "queued" || job.status === "running" || job.status === "retry_wait" }
function isBatchActive(batch: ManualDeleteBatch) { return batch.status === "queued" || batch.status === "running" }
function BatchCard({ batch, language, progressLabel }: { batch: ManualDeleteBatch; language: DeletionLanguage; progressLabel: string }) { const active = isBatchActive(batch); const needsAttention = batch.status === "failed" || batch.status === "partial" || batch.status === "cancelled"; const terminal = batch.completed_count + batch.blocked_count + batch.failed_count + batch.cancelled_count; const progress = batch.total_count ? Math.round((terminal / batch.total_count) * 100) : 0; const counts = batchCounts(batch, language); return <article className="rounded-lg border border-border bg-card p-3"><div className="flex gap-2"><div className="pt-0.5">{needsAttention ? <CircleAlert className="size-4 text-status-danger" /> : active ? <ListChecks className="size-4 text-primary" /> : <CheckCircle2 className="size-4 text-status-success" />}</div><div className="min-w-0 flex-1"><h3 className="text-sm font-medium">{batchItemCountLabel(batch.total_count, language)}</h3><p className="mt-1 text-xs text-muted-foreground">{localizedBatchStatus(batch.status, language)}</p><Progress className="mt-3" value={progress} aria-label={`${progressLabel}: ${progress}%`} /><div className="mt-1.5 flex justify-between gap-2 text-[11px] text-muted-foreground"><Badge variant="outline" className="text-[10px]">{localizedBatchStatus(batch.status, language)}</Badge><span>{terminal}/{batch.total_count}</span></div><p className="mt-1 text-[11px] text-muted-foreground">{counts}</p><ul className="mt-3 space-y-1 border-t border-border pt-2">{batch.children.map((child) => <li key={child.id} className="flex items-center justify-between gap-2 text-xs"><span className="min-w-0 truncate">{child.display_name}</span><Badge variant="outline" className="shrink-0 text-[10px]">{localizedBatchStatus(child.status, language)}</Badge></li>)}</ul></div></div></article> }
function batchCounts(batch: ManualDeleteBatch, language: DeletionLanguage) { const labels = language === "ru" ? { completed: "завершено", blocked: "заблокировано", failed: "ошибка", cancelled: "отменено" } : { completed: "completed", blocked: "blocked", failed: "failed", cancelled: "cancelled" }; return [`${labels.completed}: ${batch.completed_count}`, `${labels.blocked}: ${batch.blocked_count}`, `${labels.failed}: ${batch.failed_count}`, `${labels.cancelled}: ${batch.cancelled_count}`].join(" · ") }
function taskCountLabel(count: number, kind: "active" | "recent", language: DeletionLanguage, fallback: string) { if (language !== "ru") return `${count} ${fallback}`; if (count === 1) return `1 ${kind === "active" ? "активная" : "недавняя"}`; return `${count} ${fallback}` }
function batchItemCountLabel(count: number, language: DeletionLanguage) { if (language !== "ru") return `${count} ${count === 1 ? "item" : "items"} in batch`; const mod100 = Math.abs(count) % 100; const mod10 = mod100 % 10; const noun = mod100 >= 11 && mod100 <= 14 ? "элементов" : mod10 === 1 ? "элемент" : mod10 >= 2 && mod10 <= 4 ? "элемента" : "элементов"; return `${count} ${noun} в пакете` }
