import type { AppShellLabels, ShellLanguage } from "./app-shell"

export const SHELL_COPY: Record<ShellLanguage, AppShellLabels> = {
  en: {
    logo: "CleanArr",
    navigation: "Main navigation",
    more: "More",
    close: "Close",
    status: "Runtime status",
    live: "Live",
    dryRun: "Dry-run",
    storage: "Storage",
    storagePartial: "Partial data",
    storageUnavailable: "Storage unavailable",
    account: "Account",
    settings: "Settings",
    settingsGeneral: "General",
    settingsServices: "Connected services",
    theme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    language: "Language",
    logOut: "Log out",
    githubStars: "15 stars",
    nav: { overview: "Overview", library: "Library", downloads: "Downloads", activity: "Activity", settings: "Settings" },
    storageStatus: { healthy: "Healthy", warning: "Limited space", critical: "Critically low", unknown: "Unknown" },
  },
  ru: {
    logo: "CleanArr",
    navigation: "Основная навигация",
    more: "Ещё",
    close: "Закрыть",
    status: "Режим работы",
    live: "Рабочий",
    dryRun: "Тестовый",
    storage: "Хранилище",
    storagePartial: "Неполные данные",
    storageUnavailable: "Данные о хранилище недоступны",
    account: "Аккаунт",
    settings: "Настройки",
    settingsGeneral: "Общие",
    settingsServices: "Подключённые сервисы",
    theme: "Тема",
    themeLight: "Светлая",
    themeDark: "Тёмная",
    themeSystem: "Системная",
    language: "Язык",
    logOut: "Выйти",
    githubStars: "15 звёзд",
    nav: { overview: "Обзор", library: "Библиотека", downloads: "Загрузки", activity: "Активность", settings: "Настройки" },
    storageStatus: { healthy: "В норме", warning: "Мало места", critical: "Критически мало", unknown: "Неизвестно" },
  },
}
