"""Domain exports."""

from .errors import AuthenticationError, ExternalServiceError, ResourceNotFoundError
from .models import (
    ActionResult,
    ActionStatus,
    DownloaderRemovalResult,
    FailureReason,
    ItemType,
    JellyseerrIssue,
    JellyseerrMedia,
    JellyseerrRequest,
    MediaDeletionEvent,
    MediaFingerprint,
    OverallStatus,
    ProcessingResult,
    RadarrHistoryRecord,
    RadarrMovie,
    SafetyDecision,
    SafetyNote,
    SonarrEpisode,
    SonarrEpisodeFile,
    SonarrHistoryRecord,
    SonarrSeries,
)

__all__ = [
    "ActionResult",
    "ActionStatus",
    "AuthenticationError",
    "DownloaderRemovalResult",
    "ExternalServiceError",
    "FailureReason",
    "ItemType",
    "JellyseerrIssue",
    "JellyseerrMedia",
    "JellyseerrRequest",
    "MediaDeletionEvent",
    "MediaFingerprint",
    "OverallStatus",
    "ProcessingResult",
    "RadarrHistoryRecord",
    "RadarrMovie",
    "ResourceNotFoundError",
    "SafetyDecision",
    "SafetyNote",
    "SonarrEpisode",
    "SonarrEpisodeFile",
    "SonarrHistoryRecord",
    "SonarrSeries",
]
